#ifndef SYSTEMS_H
#define SYSTEMS_H
#include "ecs/systems/AttackSystem.h"
#include "ecs/systems/CameraSystem.h"
#include "ecs/systems/CollisionSystem.h"
#include "ecs/systems/DebugSystem.h"
#include "ecs/systems/PlayerMoveSystem.h"
#include "ecs/systems/RenderingSystem.h"
#include "ecs/systems/ScoreSystem.h"
#endif// SYSTEMS_H
